import { createApp } from 'vue';
import '@/style.scss';
import App from './App.vue';
import { ripple } from './directives/ripple';
import loading from './directives/loading';
import gradientIcon from '@/directives/gradientIcon';
import gradientText from '@/directives/gradientText';
import mask from '@/directives/mask';
import tooltip from './directives/tooltip';
import vClickOutside from 'click-outside-vue3';
import FloatingVue from 'floating-vue';
import { installIcons } from './use/icon';
const app = createApp(App).use(router);
import 'floating-vue/dist/style.css';
import router from './router';
import { createDefaultLightTheme } from './theme/default';

createDefaultLightTheme('#704aff');
app.use(FloatingVue);
app.use(vClickOutside);
installIcons(app);
app.directive('ripple', ripple);
app.directive('tooltip', tooltip);
app.directive('loading', loading);
app.directive('gradient-icon', gradientIcon);
app.directive('gradient-text', gradientText);
app.directive('mask', mask);
app.mount('#app');
